services:
  postgres:
    image: postgres:16.2-alpine
    hostname: postgres
    env_file:
      - .env/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  wiki:
    depends_on:
      - postgres
    image: requarks/wiki:2.5
    hostname: wiki
    env_file:
      - .env/postgres
      - .env/wiki
    volumes:
      - wiki-backup:/wiki/backup
    ports:
      - 80:3000
      - 443:3443
    restart: always

volumes:
  postgres-data:
  wiki-backup:
